export const getAutocompleteNames = (query, signal) => {
  const names = [
    { id: 1, firstName: 'Olivia' },
    { id: 2, firstName: 'Emma' },
    { id: 3, firstName: 'Amelia' },
    { id: 4, firstName: 'Ava' },
    { id: 5, firstName: 'Sophia' },
    { id: 6, firstName: 'Isabella' },
    { id: 7, firstName: 'Luna' },
    { id: 8, firstName: 'Mia' },
    { id: 9, firstName: 'Charlotte' },
    { id: 10, firstName: 'Evelyn' },
    { id: 11, firstName: 'Harper' },
    { id: 12, firstName: 'Scarlett' },
    { id: 13, firstName: 'Nova' },
    { id: 14, firstName: 'Aurora' },
    { id: 15, firstName: 'Ella' },
    { id: 16, firstName: 'Mila' },
    { id: 17, firstName: 'Aria' },
    { id: 18, firstName: 'Ellie' },
    { id: 19, firstName: 'Gianna' },
    { id: 20, firstName: 'Sofia' },
    { id: 21, firstName: 'Violet' },
    { id: 22, firstName: 'Layla' },
    { id: 23, firstName: 'Willow' },
    { id: 24, firstName: 'Lily' },
    { id: 25, firstName: 'Hazel' },
    { id: 26, firstName: 'Camila' },
    { id: 27, firstName: 'Avery' },
    { id: 28, firstName: 'Chloe' },
    { id: 29, firstName: 'Elena' },
    { id: 30, firstName: 'Paisley' },
    { id: 31, firstName: 'Eliana' },
    { id: 32, firstName: 'Penelope' },
    { id: 33, firstName: 'Eleanor' },
    { id: 34, firstName: 'Ivy' },
    { id: 35, firstName: 'Elizabeth' },
    { id: 36, firstName: 'Riley' },
    { id: 37, firstName: 'Isla' },
    { id: 38, firstName: 'Abigail' },
    { id: 39, firstName: 'Nora' },
    { id: 40, firstName: 'Stella' },
    { id: 41, firstName: 'Grace' },
    { id: 42, firstName: 'Zoey' },
    { id: 43, firstName: 'Emily' },
    { id: 44, firstName: 'Emilia' },
    { id: 45, firstName: 'Leilani' },
    { id: 46, firstName: 'Everly' },
    { id: 47, firstName: 'Kinsley' },
    { id: 48, firstName: 'Athena' },
    { id: 49, firstName: 'Delilah' },
    { id: 50, firstName: 'Naomi' },
    { id: 101, firstName: 'Liam' },
    { id: 102, firstName: 'Noah' },
    { id: 103, firstName: 'Oliver' },
    { id: 104, firstName: 'Elijah' },
    { id: 105, firstName: 'Mateo' },
    { id: 106, firstName: 'Lucas' },
    { id: 107, firstName: 'Levi' },
    { id: 108, firstName: 'Asher' },
    { id: 109, firstName: 'James' },
    { id: 110, firstName: 'Leo' },
    { id: 111, firstName: 'Grayson' },
    { id: 112, firstName: 'Ezra' },
    { id: 113, firstName: 'Luca' },
    { id: 114, firstName: 'Ethan' },
    { id: 115, firstName: 'Aiden' },
    { id: 116, firstName: 'Wyatt' },
    { id: 117, firstName: 'Sebastian' },
    { id: 118, firstName: 'Benjamin' },
    { id: 119, firstName: 'Mason' },
    { id: 120, firstName: 'Henry' },
    { id: 121, firstName: 'Hudson' },
    { id: 122, firstName: 'Jack' },
    { id: 123, firstName: 'Jackson' },
    { id: 124, firstName: 'Owen' },
    { id: 125, firstName: 'Daniel' },
    { id: 126, firstName: 'Alexander' },
    { id: 127, firstName: 'Maverick' },
    { id: 128, firstName: 'Kai' },
    { id: 129, firstName: 'Gabriel' },
    { id: 130, firstName: 'Carter' },
    { id: 131, firstName: 'William' },
    { id: 132, firstName: 'Logan' },
    { id: 133, firstName: 'Michael' },
    { id: 134, firstName: 'Samuel' },
    { id: 135, firstName: 'Muhammad' },
    { id: 136, firstName: 'Waylon' },
    { id: 137, firstName: 'Ezekiel' },
    { id: 138, firstName: 'Jayden' },
    { id: 139, firstName: 'Luke' },
    { id: 140, firstName: 'Lincoln' },
    { id: 141, firstName: 'Theo' },
    { id: 142, firstName: 'Jacob' },
    { id: 143, firstName: 'Josiah' },
    { id: 144, firstName: 'David' },
    { id: 145, firstName: 'Jaxon' },
    { id: 146, firstName: 'Elias' },
    { id: 147, firstName: 'Julian' },
    { id: 148, firstName: 'Theodore' },
    { id: 149, firstName: 'Isaiah' },
    { id: 150, firstName: 'Matthew' }
  ];

  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if(signal.aborted) {
        reject(signal.reason);
      }

      resolve(
        names.filter(name => 
          name.firstName.toLowerCase().includes(query.toLowerCase())
        )
      );
    }, Math.random() * 1000);
  });
};
